---
apiVersion: v1
kind: Service
metadata:
  name: my-httpd-service
  namespace: my-httpd-namespace
spec:
  selector:
    my-pod-label: httpd-pod
  ports:
    - name: http
      protocol: TCP
      port: 10000
      targetPort: 80